spring:
  application:
    name: chamda
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chamda
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  #  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: true

  #  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:chamda
#    username: sa
#    loginId:
#    driver-class-name: org.h2.Driver
server:
  servlet:
    encoding:
      charset: utf-8
      force-response: true
#server:
#  data:
#    web:
#      pageable:
#        one-indexed-parameters: true
#        default-page-size: 5