spring:
  application:
    name: chamda
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:chamda
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
#server:
#  data:
#    web:
#      pageable:
#        one-indexed-parameters: true
#        default-page-size: 5